### ISSUE TITLE
GitVersioning as a versioning solution

### ISSUE THREAD

**Issue by Twinki14** [KSPModdingLibs/KSPBuildTools#13]
I see the use of https://github.com/KSPModdingLibs/KSPBuildTools/blob/main/update-version.sh

https://github.com/dotnet/Nerdbank.GitVersioning or https://github.com/GitTools/GitVersion would provide a much more out-of-the-box solution that ties incredibly well together with GitHub actions and greatly simplifies the process you're already doing in https://github.com/KSPModdingLibs/KSPBuildTools/blob/main/update-version.sh

Basing release creation off of GitHub together with Git-based versioning would enable creators to write their own changelogs that could be automatically included in the release zip & automatically pack and version-stamp their mods

**Comment by JonnyOThan** [comment]
Thanks for the info, I wasn’t aware of these…probably would have used one if I was.

one of my goals here is to create a set of independent parts that can be customized and used individually, and not necessarily require using GitHub actions for building.  And then also stitch those together in a common reusable system.  I’d have to figure out of these packages support that (I think they do).

> enable creators to write their own changelogs that could be automatically included in the release zip & automatically pack and version-stamp their mods

The current system supports this via yaclog.  If you keep an `unreleased` section at the top of your changelog, then you can invoke `create-release.yml` with either a full version string or `—major`, `—minor`, etc.  I don’t think I’ve fully documented all that yet…

**Comment by drewcassidy** [comment]
I put something together that does this. 

https://github.com/KSPModdingLibs/Shabby/blob/3f1ed17419afa809d53bcabc728621e732df41a6/Source/Shabby.csproj#L25-L63

The idea is that assembly version would be entirely driven by git tags, not by yaclog. Yaclog can still be used to track changeling information and make it usable to GitHub releases or space dock, but would no longer be a dependency. If the current commit is on a tag, that tag is used as the version. otherwise it finds the most recent tag and increments the patch, and uses the number of commits since as a build number. 

The release action can still exist, as just a way to call `yaclog release` through the GitHub UI. then the main release workflow would pick up the new tag and turn it into a release.

**Comment by JonnyOThan** [comment]
>  If the current commit is on a tag, that tag is used as the version

Forgive me, I'm not super well versed in usages of git tags.  AFAIK It's just a name for a specific commit right?

As I understand it, the problem here is that I'd like the tagged version to reflect the state of the repo that the release was created from.  But that means you need to *commit* updated changelog, .version files, etc and *then* tag that commit.

I can totally get on board with using the previous tag in order to do figure out what the version should be for the `--major`, `--minor`, `--patch` options though.

**Comment by drewcassidy** [comment]
Close. Im imagining the .version file would just be a stub that only gets populated with the version information in the *build* script (already implemented [here](https://github.com/KSPModdingLibs/Shabby/blob/d1efb8e639af6ba4d95beb042a880f3815975881/Source/Shabby.csproj#L69-L81))

So workflow is:
1a) Developer manually dispatches the [release](https://github.com/KSPModdingLibs/Shabby/blob/version-gen/.github/workflows/release.yml) workflow, which runs yaclog, then pushes the resulting commit and tag back to the repo. The only file it changes is the changelog to signal that the current version has changed, as well as creating a git tag.
1b) OR the developer does the same locally. 

\2) the [build action](https://github.com/KSPModdingLibs/Shabby/blob/version-gen/.github/workflows/build.yml) is triggered by a push to a tag. This compiles everything, packages it, and deploys it

**Comment by JonnyOThan** [comment]
> Close. Im imagining the .version file would just be a stub that only gets populated with the version information in the build script (already implemented [here](https://github.com/KSPModdingLibs/Shabby/blob/d1efb8e639af6ba4d95beb042a880f3815975881/Source/Shabby.csproj#L69-L81))

how does this work for local iteration then? Won’t you constantly be sitting on a modified .version file?

**Comment by drewcassidy** [comment]
You mean for comparison against? That's why I include it in the github release.

**Comment by JonnyOThan** [comment]
> You mean for comparison against? That's why I include it in the github release.

No, the .version file contains a URL which AVC fetches from within the game to see if a mod has been updated.  Typically that’s in the GitHub repo somewhere.  So it needs to be committed on each release.

**Comment by drewcassidy** [comment]
Unfortunately GitVersion doesnt work with net48 projects at the moment [bug report](https://github.com/GitTools/GitVersion/issues/4189)

I have my own hacked together version using `git describe` I can try to harden a bit. I don't know if the GitVersion project is likely to support our weird use case...

**Comment by Twinki14** [comment]
> Unfortunately GitVersion doesnt work with net48 projects at the moment [bug report](https://github.com/GitTools/GitVersion/issues/4189)
> 
> I have my own hacked together version using `git describe` I can try to harden a bit. I don't know if the GitVersion project is likely to support our weird use case...

You can always go back to a version before 5.x, fairly easy to do in GitHub Actions.

https://github.com/dotnet/Nerdbank.GitVersioning Is another solution that's specific to .NET, and very likely has nice net48 support.

I'd spend some time coming up with some proper Git-based versioning and create a PR, but my solution would solely live in GitHub and rely on the use of GitHub Releases & GitHub Actions. Which goes against what @JonnyOThan had mentioned early on in the thread.

I personally don't see any point to supporting anything else, having it all in GitHub removes the need to have ultra-specific local configurations for cutting releases, and makes it incredibly easy for any interested KSP modders who want to fork your mod to try some stuff out and maybe cut their own releases.

**Comment by drewcassidy** [comment]
I still need to be able to build the mod locally to develop it. Not having that is a non-started

**Comment by Twinki14** [comment]
> I still need to be able to build the mod locally to develop it. Not having that is a non-starter
> 
> Nerdbank.GitVersioning still pulls from a json version file which is weird... I don't understand why it cant just use `git describe`

Yeah, the actual mod build process would still work locally. I'm only strongly suggesting the CI/CD only live in GitHub. 

I've built custom versioning for GHA that uses `git` directly in the past, it sorta works.

GitVersion works independently from the dotnet source, the only benefit to using it alongside it is that it would stamp the assembly. So you could still use it and find something else that can stamp the mods assembly in CI with the semantic version GitVersion gives you.

**Comment by drewcassidy** [comment]
Miniver doesn't increment the patch number

**Comment by Twinki14** [comment]
> Miniver doesn't increment the patch number

Goes off git tag, so the idea would be that you generate a semantic v2 version using in CI using GitVersion, then `git tag` using that version, and MinVer will stamp the assembly.

**Comment by drewcassidy** [comment]
I don't understand, msbuild already stamps the assembly with the version. 

regardless, I already wrote #27

**Comment by drewcassidy** [comment]
Looking at it again, MinVer is actually perfect

however I don't think it has any place as part of KSPBuildTools. its easy enough to just add it to your csproj alongside KSPBuildTools

**Comment by drewcassidy** [comment]
Closing this as it requires no changes from KSPBuildTools to use
