### ISSUE TITLE
Idea: make KSPBuildTools available through nuget

### ISSUE THREAD

**Issue by drewcassidy** [KSPModdingLibs/KSPBuildTools#24]
I *Think* that msbuild stuff can be put on nuget on its own. That would allow usage without having to deal with submodules

**Comment by Twinki14** [comment]
Would definitely help keep it up-to-date, there might be a MSBuild nuget package that you'd reference?

**Comment by Twinki14** [comment]
https://github.com/adamralph/minver Did just stumble upon this, much more minimal than GitVersion or Nerdbank and uses Git Tags directly
