### ISSUE TITLE
consider adding a msbuild target for assembling the release zip

### ISSUE THREAD

**Issue by JonnyOThan** [KSPModdingLibs/KSPBuildTools#7]
https://github.com/HebaruSan/KerbalChangelog/blob/028b0dd237b2aee64e674a73ca9e19973818411d/Source/KerbalChangelog.csproj#L77

This would allow people to do this locally, but it should probably replace the github actions stuff if we do it.

**Comment by drewcassidy** [comment]
Im not sure this is a good idea, since building the release zip is not something that benefits from msbuild, and is an identical series of steps for part-only mods which presumably will not have a csproj file.

**Comment by JonnyOThan** [comment]
Good point.
